### ISSUE TITLE
502 bad gateway

### ISSUE THREAD

**Issue by mattbk** [YunoHost-Apps/airsonic_ynh#38]
I'm not sure if the power failure caused the problem, but a restart does not change anything. I can start the airsonic service through yunhohost admin interface, but it crashes after several minutes.

yunohost is installed on an x86_64 machine hard drive (not an SD card). Any insight is appreciated.

Airsonic version 10.6.2~ynh2.

Log is here:
```
Oct 02 22:24:40 amiok.net systemd[1]: Started airsonic Media Server.
Oct 02 22:24:46 amiok.net java[12647]:            _                       _
Oct 02 22:24:46 amiok.net java[12647]:      /\   (_)                     (_)
Oct 02 22:24:46 amiok.net java[12647]:     /  \   _ _ __  ___  ___  _ __  _  ___
Oct 02 22:24:46 amiok.net java[12647]:    / /\ \ | | '__|/ __|/ _ \| '_ \| |/ __|
Oct 02 22:24:46 amiok.net java[12647]:   / ____ \| | |   \__ \ (_) | | | | | (__
Oct 02 22:24:46 amiok.net java[12647]:  /_/    \_\_|_|   |___/\___/|_| |_|_|\___|
Oct 02 22:24:46 amiok.net java[12647]:
Oct 02 22:24:46 amiok.net java[12647]:                         10.6.2-RELEASE
Oct 02 22:24:47 amiok.net java[12647]: 2020-10-02 22:24:47.408  INFO --- org.airsonic.player.Application          : Starting Application v10.6.2-RELEASE on amiok.net with PID 12647 (/opt/yunohost/airsonic/airsonic.war started by airsonic in /)
Oct 02 22:24:47 amiok.net java[12647]: 2020-10-02 22:24:47.446  INFO --- org.airsonic.player.Application          : The following profiles are active: legacy
Oct 02 22:24:52 amiok.net java[12647]: WARNING: An illegal reflective access operation has occurred
Oct 02 22:24:52 amiok.net java[12647]: WARNING: Illegal reflective access by org.springframework.cglib.core.ReflectUtils$1 (jar:file:/opt/yunohost/airsonic/airsonic.war!/WEB-INF/lib/spring-core-4.3.25.RELEASE.jar!/) to method java.lang.ClassLoader.defineClass(java.lang.
Oct 02 22:24:52 amiok.net java[12647]: WARNING: Please consider reporting this to the maintainers of org.springframework.cglib.core.ReflectUtils$1
Oct 02 22:24:52 amiok.net java[12647]: WARNING: Use --illegal-access=warn to enable warnings of further illegal reflective access operations
Oct 02 22:24:52 amiok.net java[12647]: WARNING: All illegal access operations will be denied in a future release
Oct 02 22:25:05 amiok.net java[12647]: 2020-10-02 22:25:05.578  INFO --- l.executor.jvm.JdbcExecutor              : SELECT COUNT(*) FROM DATABASECHANGELOGLOCK
Oct 02 22:25:05 amiok.net java[12647]: 2020-10-02 22:25:05.615  INFO --- l.executor.jvm.JdbcExecutor              : SELECT COUNT(*) FROM DATABASECHANGELOGLOCK
Oct 02 22:25:05 amiok.net java[12647]: 2020-10-02 22:25:05.700  INFO --- l.l.StandardLockService                  : Successfully acquired change log lock
...skipping...
Oct 02 22:25:32 amiok.net java[12647]:         at org.springframework.security.config.annotation.authentication.configurers.ldap.LdapAuthenticationProviderConfigurer$ContextSourceBuilder.access$500(LdapAuthenticationProviderConfigurer.java:447) ~[spring-security-config-
Oct 02 22:25:32 amiok.net java[12647]:         at org.springframework.security.config.annotation.authentication.configurers.ldap.LdapAuthenticationProviderConfigurer.getContextSource(LdapAuthenticationProviderConfigurer.java:607) ~[spring-security-config-4.2.13.RELEASE.
Oct 02 22:25:32 amiok.net java[12647]:         at org.springframework.security.config.annotation.authentication.configurers.ldap.LdapAuthenticationProviderConfigurer.build(LdapAuthenticationProviderConfigurer.java:77) ~[spring-security-config-4.2.13.RELEASE.jar!/:4.2.13
Oct 02 22:25:32 amiok.net java[12647]:         at org.springframework.security.config.annotation.authentication.configurers.ldap.LdapAuthenticationProviderConfigurer.configure(LdapAuthenticationProviderConfigurer.java:391) ~[spring-security-config-4.2.13.RELEASE.jar!/:4
Oct 02 22:25:32 amiok.net java[12647]:         at org.springframework.security.config.annotation.authentication.configurers.ldap.LdapAuthenticationProviderConfigurer.configure(LdapAuthenticationProviderConfigurer.java:59) ~[spring-security-config-4.2.13.RELEASE.jar!/:4.
Oct 02 22:25:32 amiok.net java[12647]:         at org.springframework.security.config.annotation.AbstractConfiguredSecurityBuilder.configure(AbstractConfiguredSecurityBuilder.java:384) ~[spring-security-config-4.2.13.RELEASE.jar!/:4.2.13.RELEASE]
Oct 02 22:25:32 amiok.net java[12647]:         at org.springframework.security.config.annotation.AbstractConfiguredSecurityBuilder.doBuild(AbstractConfiguredSecurityBuilder.java:330) ~[spring-security-config-4.2.13.RELEASE.jar!/:4.2.13.RELEASE]
Oct 02 22:25:32 amiok.net java[12647]:         at org.springframework.security.config.annotation.AbstractSecurityBuilder.build(AbstractSecurityBuilder.java:41) ~[spring-security-config-4.2.13.RELEASE.jar!/:4.2.13.RELEASE]
Oct 02 22:25:32 amiok.net java[12647]:         at org.springframework.security.config.annotation.authentication.configuration.AuthenticationConfiguration.getAuthenticationManager(AuthenticationConfiguration.java:105) ~[spring-security-config-4.2.13.RELEASE.jar!/:4.2.13.
Oct 02 22:25:32 amiok.net java[12647]:         at org.springframework.security.config.annotation.web.configuration.WebSecurityConfigurerAdapter.authenticationManager(WebSecurityConfigurerAdapter.java:262) ~[spring-security-config-4.2.13.RELEASE.jar!/:4.2.13.RELEASE]
Oct 02 22:25:32 amiok.net java[12647]:         at org.airsonic.player.security.GlobalSecurityConfig$ExtSecurityConfiguration.jwtAuthFilter(GlobalSecurityConfig.java:92) ~[classes!/:10.6.2-RELEASE]
Oct 02 22:25:32 amiok.net java[12647]:         at org.airsonic.player.security.GlobalSecurityConfig$ExtSecurityConfiguration$$EnhancerBySpringCGLIB$$cc8e3c5c.CGLIB$jwtAuthFilter$1(<generated>) ~[classes!/:10.6.2-RELEASE]
Oct 02 22:25:32 amiok.net java[12647]:         at org.airsonic.player.security.GlobalSecurityConfig$ExtSecurityConfiguration$$EnhancerBySpringCGLIB$$cc8e3c5c$$FastClassBySpringCGLIB$$35da5c33.invoke(<generated>) ~[classes!/:10.6.2-RELEASE]
Oct 02 22:25:32 amiok.net java[12647]:         at org.springframework.cglib.proxy.MethodProxy.invokeSuper(MethodProxy.java:228) ~[spring-core-4.3.25.RELEASE.jar!/:4.3.25.RELEASE]
Oct 02 22:25:32 amiok.net java[12647]:         at org.springframework.context.annotation.ConfigurationClassEnhancer$BeanMethodInterceptor.intercept(ConfigurationClassEnhancer.java:358) ~[spring-context-4.3.25.RELEASE.jar!/:4.3.25.RELEASE]
Oct 02 22:25:32 amiok.net java[12647]:         at org.airsonic.player.security.GlobalSecurityConfig$ExtSecurityConfiguration$$EnhancerBySpringCGLIB$$cc8e3c5c.jwtAuthFilter(<generated>) ~[classes!/:10.6.2-RELEASE]
Oct 02 22:25:32 amiok.net java[12647]:         at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[na:na]
Oct 02 22:25:32 amiok.net java[12647]:         at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[na:na]
Oct 02 22:25:32 amiok.net java[12647]:         at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[na:na]
Oct 02 22:25:32 amiok.net java[12647]:         at java.base/java.lang.reflect.Method.invoke(Method.java:566) ~[na:na]
Oct 02 22:25:32 amiok.net java[12647]:         at org.springframework.beans.factory.support.SimpleInstantiationStrategy.instantiate(SimpleInstantiationStrategy.java:162) ~[spring-beans-4.3.25.RELEASE.jar!/:4.3.25.RELEASE]
Oct 02 22:25:32 amiok.net java[12647]:         ... 27 common frames omitted
Oct 02 22:25:33 amiok.net systemd[1]: airsonic.service: Main process exited, code=exited, status=1/FAILURE
Oct 02 22:25:33 amiok.net systemd[1]: airsonic.service: Failed with result 'exit-code'.
```

**Comment by madtibo** [comment]
Hello,

I had the same problem with yunohost 3.8 and 4.0.
When airsonic was used, the java program would go at 100% CPU.
Not sure why and how it causes an application crash... but a crash there was.

I switched to [navidrome](https://install-app.yunohost.org/?app=navidrome) and it is working smoothly.

Cordialement,

**Comment by yalh76** [comment]
should be fixed for now
